// World countries — South Africa listed first as the app default.
export const COUNTRIES = [
  'South Africa',
  'Zimbabwe',
  'Botswana',
  'Namibia',
  'Lesotho',
  'Eswatini',
  'Mozambique',
  'Zambia',
  'Malawi',
  'Angola',
  'Kenya',
  'Tanzania',
  'Uganda',
  'Nigeria',
  'Ghana',
  'Egypt',
  'Morocco',
  'Mauritius',
  'United Kingdom',
  'Ireland',
  'United States',
  'Canada',
  'Australia',
  'New Zealand',
  'Germany',
  'France',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  'Italy',
  'Spain',
  'Portugal',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Czech Republic',
  'Hungary',
  'Romania',
  'Greece',
  'Turkey',
  'Russia',
  'Ukraine',
  'United Arab Emirates',
  'Saudi Arabia',
  'Qatar',
  'Israel',
  'India',
  'China',
  'Japan',
  'South Korea',
  'Singapore',
  'Hong Kong',
  'Malaysia',
  'Thailand',
  'Indonesia',
  'Philippines',
  'Vietnam',
  'Pakistan',
  'Bangladesh',
  'Brazil',
  'Mexico',
  'Argentina',
  'Chile',
  'Colombia',
  'Peru',
]

export const DEFAULT_COUNTRY = 'South Africa'

export const COUNTRY_DIAL_CODES = [
  { country: 'South Africa', code: '+27' },
  { country: 'Zimbabwe',     code: '+263' },
  { country: 'Botswana',     code: '+267' },
  { country: 'Namibia',      code: '+264' },
  { country: 'Lesotho',      code: '+266' },
  { country: 'Eswatini',     code: '+268' },
  { country: 'Mozambique',   code: '+258' },
]
