// World currencies — South African Rand listed first as the app default.
export const CURRENCIES = [
  'South African Rand - ZAR',
  'US Dollar - USD',
  'Euro - EUR',
  'British Pound - GBP',
  'Japanese Yen - JPY',
  'Swiss Franc - CHF',
  'Canadian Dollar - CAD',
  'Australian Dollar - AUD',
  'New Zealand Dollar - NZD',
  'Chinese Yuan - CNY',
  'Indian Rupee - INR',
  'Botswana Pula - BWP',
  'Namibian Dollar - NAD',
  'Lesotho Loti - LSL',
  'Eswatini Lilangeni - SZL',
  'Mozambican Metical - MZN',
  'Zimbabwean Dollar - ZWL',
  'Zambian Kwacha - ZMW',
  'Kenyan Shilling - KES',
  'Nigerian Naira - NGN',
  'Ghanaian Cedi - GHS',
  'Egyptian Pound - EGP',
  'Angolan Kwanza - AOA',
  'Mauritian Rupee - MUR',
  'UAE Dirham - AED',
  'Saudi Riyal - SAR',
  'Singapore Dollar - SGD',
  'Hong Kong Dollar - HKD',
  'South Korean Won - KRW',
  'Brazilian Real - BRL',
  'Mexican Peso - MXN',
  'Russian Ruble - RUB',
  'Turkish Lira - TRY',
  'Polish Zloty - PLN',
  'Swedish Krona - SEK',
  'Norwegian Krone - NOK',
  'Danish Krone - DKK',
  'Thai Baht - THB',
  'Indonesian Rupiah - IDR',
  'Malaysian Ringgit - MYR',
  'Philippine Peso - PHP',
  'Vietnamese Dong - VND',
  'Pakistani Rupee - PKR',
  'Bangladeshi Taka - BDT',
  'Israeli New Shekel - ILS',
  'Argentine Peso - ARS',
  'Chilean Peso - CLP',
  'Colombian Peso - COP',
  'Peruvian Sol - PEN',
  'Czech Koruna - CZK',
  'Hungarian Forint - HUF',
  'Romanian Leu - RON',
  'Ukrainian Hryvnia - UAH',
]

export const DEFAULT_CURRENCY = 'South African Rand - ZAR'
